version: '2'
services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=3dodPaTXF5

    web_en:
        build:
            context: ./web_en
            dockerfile: Dockerfile
        ports:
            - "8081:80"
        links:
            - db
            - parsoid
            - elasticsearch
            - memcache
        environment:
            - MW_SITE_SERVER=//localhost:8081
            - MW_SITE_NAME=Datastd
            - MW_SITE_LANG=en
            - MW_DEFAULT_SKIN=vector
            - MW_ENABLE_UPLOADS=1
            - MW_USE_INSTANT_COMMONS=0
            - MW_ADMIN_USER=admin
            - MW_ADMIN_PASS=q32Gx7Amg7
            - MW_DB_NAME=mediawiki_en
            - MW_DB_USER=mwuser_en
            - MW_DB_PASS=18fj38vz2@
            - MW_DB_INSTALLDB_USER=root
            - MW_DB_INSTALLDB_PASS=3dodPaTXF5
            - MW_AUTOUPDATE=true

    web_ru:
        build:
            context: ./web_ru
            dockerfile: Dockerfile
        ports:
            - "8082:80"
        links:
            - db
            - parsoid
            - elasticsearch
            - memcache
        environment:
            - MW_SITE_SERVER=//localhost:8082
            - MW_SITE_NAME=Datastd
            - MW_SITE_LANG=ru
            - MW_DEFAULT_SKIN=vector
            - MW_ENABLE_UPLOADS=1
            - MW_USE_INSTANT_COMMONS=0
            - MW_ADMIN_USER=admin
            - MW_ADMIN_PASS=q32Gx7Amg7
            - MW_DB_NAME=mediawiki_ru
            - MW_DB_USER=mwuser_ru
            - MW_DB_PASS=8Xgat7mUKa
            - MW_DB_INSTALLDB_USER=root
            - MW_DB_INSTALLDB_PASS=3dodPaTXF5
            - MW_AUTOUPDATE=true

    web_de:
        build:
            context: ./web_de
            dockerfile: Dockerfile
        ports:
            - "8083:80"
        links:
            - db
            - parsoid
            - elasticsearch
            - memcache
        environment:
            - MW_SITE_SERVER=//localhost:8083
            - MW_SITE_NAME=Datastd
            - MW_SITE_LANG=de
            - MW_DEFAULT_SKIN=vector
            - MW_ENABLE_UPLOADS=1
            - MW_USE_INSTANT_COMMONS=0
            - MW_ADMIN_USER=admin
            - MW_ADMIN_PASS=q32Gx7Amg7
            - MW_DB_NAME=mediawiki_de
            - MW_DB_USER=mwuser_de
            - MW_DB_PASS=9h7vjas!f7
            - MW_DB_INSTALLDB_USER=root
            - MW_DB_INSTALLDB_PASS=3dodPaTXF5
            - MW_AUTOUPDATE=true

    memcache:
        build:
            context: ./memcache
            dockerfile: Dockerfile

    parsoid:
        build:
            context: ./parsoid
            dockerfile: Dockerfile

    elasticsearch:
        build:
            context: ./elasticsearch
            dockerfile: Dockerfile
